Repository ably/ably-flutter, pull requests merged in 2022-01, with the labels that each got.

#259 SDK Dart platform code improvements
  README.md
  UPDATING.md
  example/lib/push_notifications/push_notification_handlers.dart
  lib/src/common/common.dart
  lib/src/common/src/ably_base.dart
  lib/src/platform/platform_internal.dart
  lib/src/platform/src/background_android_isolate_platform.dart
  lib/src/platform/src/cipher_params_internal.dart
  lib/src/platform/src/codec.dart
  lib/src/platform/src/method_call_handler.dart
  lib/src/platform/src/push_activation_events_internal.dart
  lib/src/platform/src/push_channel_native.dart
  lib/src/platform/src/push_native.dart
  lib/src/platform/src/push_notification_events_internal.dart
  lib/src/platform/src/realtime/realtime.dart
  lib/src/platform/src/realtime/realtime_channel.dart
  lib/src/platform/src/rest/rest.dart
  lib/src/platform/src/rest/rest_channels.dart
  lib/src/push_notifications/src/push.dart
  lib/src/push_notifications/src/push_channel.dart
  test/ably_flutter_plugin_test.dart
  test/rest/channel_test.dart
  test/rest/channels_test.dart
Labels: enhancement

#261 Emphasize Ably product in descriptions (pubspec, readme)
  CONTRIBUTING.md
  README.md
  ios/Classes/AblyFlutter.m
  ios/Classes/types/AblyFlutterClientOptions.m
  lib/src/platform/src/codec.dart
Labels: enhancement

#262 Rename variables to be more meaningful
  ios/Classes/codec/AblyFlutterReader.m
Labels: enhancement

#280 Add documentation about actions required to make Ably Flutter push work across multiple environments
  PushNotifications.md
Labels: docs

#265 Example app: "release" channel button
  example/lib/ui/realtime_sliver.dart
  lib/src/platform/src/realtime/realtime_channels.dart
  lib/src/platform/src/rest/rest_channels.dart
Labels: bug

#289 Add workaround for firebase messaging
  PushNotifications.md
Labels: docs
