Repository ably/ably-flutter, pull requests merged in 2022-02, with the labels that each got.

#309 Readme enchancements for example app
  .gitignore
  .vscode/launch.json
  README.md
Labels: docs

#312 Android embedding v2
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/res/values/styles.xml
  example/android/build.gradle
  example/pubspec.lock
  example/pubspec.yaml
  pubspec.lock
  pubspec.yaml
  test_integration/android/app/build.gradle
  test_integration/android/app/src/main/AndroidManifest.xml
  test_integration/android/build.gradle
Labels: bug, maintenance

#313 Channel resumed parameter now has to be non-null
  ios/Classes/codec/AblyFlutterWriter.m
  lib/src/platform/src/codec.dart
  lib/src/realtime/src/channel_state_event.dart
Labels: bug

#307 Separate activation broadcast receiver from channel handler class
  android/src/main/java/io/ably/flutter/plugin/AblyFlutter.java
  android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java
  android/src/main/java/io/ably/flutter/plugin/push/PushActivationEventHandlers.java
  android/src/main/java/io/ably/flutter/plugin/push/PushActivationReceiver.java
Labels: bug, code-quality

#333 Encrypted channels integration testing
  test_integration/lib/config/test_constants.dart
  test_integration/lib/config/test_factory.dart
  test_integration/lib/config/test_names.dart
  test_integration/lib/test/realtime/realtime_encrypted_publish_test.dart
  test_integration/lib/test/rest/rest_encrypted_publish_test.dart
  test_integration/test_driver/test_implementation/realtime_tests.dart
  test_integration/test_driver/test_implementation/rest_tests.dart
  test_integration/test_driver/tests_config.dart
Labels: test-infrastructure

#338 Updated Firebase Cloud messaging dependency on Android to version 23.0.0
  android/build.gradle
Labels: maintenance

#310 Time function implementation
  android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java
  android/src/main/java/io/ably/flutter/plugin/generated/PlatformConstants.java
  bin/codegen_context.dart
  example/lib/ui/realtime_sliver.dart
  example/lib/ui/rest_sliver.dart
  ios/Classes/AblyFlutter.m
  ios/Classes/codec/AblyPlatformConstants.h
  ios/Classes/codec/AblyPlatformConstants.m
  lib/src/generated/platform_constants.dart
  lib/src/platform/src/platform_object.dart
  lib/src/platform/src/realtime/realtime.dart
  lib/src/platform/src/rest/rest.dart
  test_integration/lib/config/test_factory.dart
  test_integration/lib/config/test_names.dart
  test_integration/lib/test/realtime/realtime_time_test.dart
  test_integration/lib/test/rest/rest_time_test.dart
  test_integration/test_driver/test_implementation/realtime_tests.dart
  test_integration/test_driver/test_implementation/rest_tests.dart
  test_integration/test_driver/tests_config.dart
Labels: enhancement

#328 Removed deprecated registration method from Android Embedding V1
  android/src/main/java/io/ably/flutter/plugin/AblyFlutter.java
Labels: maintenance

#336 Remove deprecated ApplicationState docs reference
  lib/src/push_notifications/src/push_notification_events.dart
Labels: docs

#337 Update sample app message encryption
  example/lib/constants.dart
  example/lib/encrypted_messaging_service.dart
  example/lib/main.dart
  example/lib/ui/ably_service.dart
  example/lib/ui/message_encryption/message_encryption_sliver.dart
  example/lib/ui/realtime_sliver.dart
  example/lib/ui/rest_sliver.dart
  example/lib/ui/utilities.dart
Labels: maintenance
